project:
  type: website

website:
  title: "Dev-Sec-Wiki"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gar-rock/dev-sec-wiki
      - icon: linkedin
        href: https://www.linkedin.com/in/garrison-lerock/
format:
  html:
    theme: darkly
    css: styles.css



